#! /bin/sh

PREREQ="cryptroot"

prereqs() {
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions

touch /boot/yubikey-challenge

copy_exec /usr/bin/ykchalresp
cp /boot/yubikey-challenge "${DESTDIR}/etc/yubikey-challenge"
cp /usr/share/ykfde/ykfde-keyscript "${DESTDIR}/sbin/ykfde-keyscript"

exit 0
