#! /bin/sh

udevadm settle

if [ -e /etc/default/ykfde ]; then
	. /etc/default/ykfde
fi

chalresp() {
	echo $(ykchalresp -${YK_SLOT-2} -H -x "$(cat /etc/yubikey-challenge)"
			) # TODO restore
	return ${?}
}

echo "Unlocking the disk $cryptsource ($crypttarget)" >&2

cat /etc/yubikey-challenge >&2 # TODO rm line
status=1
if [ -s /etc/yubikey-challenge ]; then
	echo "Read from key" >&2 # TODO rm line
	key=$(chalresp)
	if [ $? -ne 0 ]; then
		echo "Insert your Yubikey or press enter to use password unlocking" >&2
		read a
		key=$(chalresp)
	fi
	status=${?}
fi

if [ "$status" -eq 0 ]; then
	echo "Using Yubikey for unlocking" >&2
	echo "Status: $status" >&2 # TODO rm line
	echo "Key: $key" >&2 # TODO rm line
	echo -n "$key"
else
	msg="Enter passphrase: "
	if [ -x /bin/plymouth ] && plymouth --ping; then
		script="plymouth ask-for-password --prompt"
	else
		script="/lib/cryptsetup/askpass"
	fi
	exec $script "$msg"
fi

mkdir -p /dev/.run/ykfde
chmod 700 /dev/.run/ykfde
echo "$cryptsource" > /dev/.run/ykfde/cryptsource

exit 0
