#! /bin/sh

udevadm settle

if [ -e /etc/default/ykfde ]; then
	. /etc/default/ykfde
fi

chalresp() {
	key=$(ykchalresp -${YK_SLOT-2} -H -x "$(cat /etc/yubikey-challenge)"
			) # TODO restore
	if [ $? -eq 0 ]; then
		echo "$key"
	fi
}

echo "Unlocking the disk $cryptsource ($crypttarget)" >&2

cat /etc/yubikey-challenge >&2 # TODO rm line
key=""
if [ -s /etc/yubikey-challenge ]; then
	echo "Read from key" >&2 # TODO rm line
	key=$(chalresp)
	if [ -z "$key" ]; then
		echo "Insert your Yubikey or press enter to use password unlocking" >&2
		read a
		key=$(chalresp)
	fi
fi

if [ -n "$key" ]; then
	echo "Using Yubikey for unlocking" >&2
	echo "Status: $status" >&2 # TODO rm line
	echo "Key: $key" >&2 # TODO rm line
	echo -n "$key"
else
	msg="Enter passphrase: "
	if [ -x /bin/plymouth ] && plymouth --ping; then
		script="plymouth ask-for-password --prompt"
	else
		script="/lib/cryptsetup/askpass"
	fi
	exec $script "$msg"
fi

mkdir -p /dev/.run/ykfde
chmod 700 /dev/.run/ykfde
echo "$cryptsource" > /dev/.run/ykfde/cryptsource

exit 0
