#! /bin/sh

udevadm settle

chalresp() {
	echo $(ykchalresp "$(cat /etc/yubikey-challenge)" \
			2>/dev/null)
	return ${?}
}

echo "Unlocking the disk $cryptsource ($crypttarget)" >&2

key=$(chalresp)
if [ $? -ne 0 ]; then
	echo "Insert your Yubikey or press enter to use password unlocking" >&2
	read a
	key=$(chalresp)
fi

if [ $? -eq 0 ]; then
	echo "Using Yubikey for unlocking" >&2
	echo -n "$key"
else
	msg="Enter passphrase: "
	if [ -x /bin/plymouth ] && plymouth --ping; then
		script="plymouth ask-for-password --prompt"
	else
		script="/lib/cryptsetup/askpass"
	fi
	exec $script "$msg"
fi

mkdir -p /dev/.run/ykfde
chmod 700 /dev/.run/ykfde
echo "$cryptsource" > /dev/.run/ykfde/cryptsource

exit 0
