#!/bin/sh

CHALLENGE_FILE="/boot/yubikey-challenge"
ERROR_LOG="/var/log/ykfde"

PREREQ="cryptroot"

prereqs()
{
    echo "$PREREQ"
}

case $1 in
prereqs)
    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

manual_add_modules hid_generic usbhid usbcore ehci_hcd ehci_pci
copy_exec /usr/bin/ykchalresp

# read defaults..
if [ -e /etc/default/ykfde ]; then
    . /etc/default/ykfde
    # now copy them to the initrd
    mkdir "${DESTDIR}/etc/default"
    cp /etc/default/ykfde "${DESTDIR}/etc/default/ykfde"
fi

touch ${ERROR_LOG}
touch ${CHALLENGE_FILE}
cp ${CHALLENGE_FILE} "${DESTDIR}/etc/yubikey-challenge"
cp /usr/share/ykfde/ykfde-keyscript "${DESTDIR}/sbin/ykfde-keyscript"
exit 0
